### PR TITLE
Multiple footer improvements and fix for #1206

### PR DESCRIPTION
**Pull request by pcbulai**
1. Because the contributors list from the footer was pretty big, I modified it so now we're displaying the 20 most active ones while providing a link to the repo's [contributors](https://github.com/angular-ui/angular-google-maps/graphs/contributors) page for the rest of them
2. Contributors avatars now link to real GitHub profiles(previously were linked to api.github.com/users/username)
3. Swapped out the static "© 2013 - 2014" in favour of dynamic value for current year
4. Fixed https://github.com/angular-ui/angular-google-maps/issues/1206

### CODE REVIEW

**Comment by nmccready** [comment]
LGTM

**Comment by cthrax** [comment]
Nice! Thanks for the contribution!

**Comment by nmccready** [comment]
just pushed gh-pages

**Comment by pcbulai** [comment]
Thank you! :+1:

**Pull request merged**
