### PR TITLE
fixed doc according to issue #864

### PR DESCRIPTION
**Pull request by escapedcat**
This should fix issue #864

### CODE REVIEW

**Comment by nmccready** [comment]
Cool ty, for other users he looked [here](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/map.coffee#L105)

**Comment by nmccready** [comment]
Actually can you PR this against website? website is for master and website-develop is for the 2.1 release. Its harder for me to cherry pick (very hard) as they have diverged slightly.

**Comment by nmccready** [comment]
Closing for PR to be redirected to the website branch.

**Comment by escapedcat** [comment]
will do

**Pull request closed without merging**
