### PR TITLE
Update Search Box with ng-model example

### PR DESCRIPTION
**Pull request by kandizzy**
Helps avoid further confusion #1076

### CODE REVIEW

**Comment by nmccready** [comment]
Something is fishy about this PR; we should only see changes from you @kandizzy. Why are commits from me and another person showing? Was there a rebase?

**Comment by kandizzy** [comment]
I hadn't synced my fork in some time. I actually tried a rebase and ditched it, so this:
https://github.com/kandizzy/angular-google-maps/commit/a39afe7c9f36c3e58465ef5bd6079aea0158cd68
 is just `git pull` from the upstream remote on a completely fresh copy of my fork.

This is odd though
https://github.com/kandizzy/angular-google-maps/commit/1f32705cf4d8f2f6505e2393b05ead0282b3d602

Did that default template fix get removed at some point?

**Comment by nmccready** [comment]
Can you just save off or cherry pick your changes to a clean fork of this? Or branch your work to some branch name. Then delete your copy of your master branch. Then get a clean copy of the master branch by branching from the remote origin/master.

**Comment by kandizzy** [comment]
cleaned this up with a soft reset

**Comment by nmccready** [comment]
LGTM

**Pull request merged**
