### PR TITLE
check maptype properties before refresh

### PR DESCRIPTION
**Pull request by eczajk1**
Proposed solution to item that was piggy-backed onto issue #1542 .

Idea is to check equality on specific properties of options object -
then trigger the map refresh.

So if your maptype (e.g. cartodb layer) relies on additional
properties/functions that are subject to change - but do not require a
map refresh, you won't get the flickering effect.

### CODE REVIEW

**Comment by eczajk1** [comment]
is the failed travis check a known issue?  I was running into the same thing in my env - before touching any code.

**Comment by nmccready** [comment]
Yeah thats not you I gotta figure out what wrong with the logger on the master branch.

**Comment by nmccready** [comment]
I'll have it patched soon, the problem is index.js in the logger is for node/ browserify/ commonjs only now.

**Comment by nmccready** [comment]
Merge in updates and I think it should pass now.

**Comment by nmccready** [comment]
LGTM

**Pull request merged**
