### PR TITLE
Quick Fix on the spacing of the coffeescript file for Lodash 4 compability

### PR DESCRIPTION
**Pull request by armyofda12mnkeys**
Sorry ... it compiles now and corresponding JS after compilation looks good...  
I had bad spacing in last PR.

### CODE REVIEW

**Comment by nmccready** [comment]
LGTM

**Comment by armyofda12mnkeys** [comment]
btw @nmccready, do you usually compile the actual js file so its available in dist? 
I just submitted the coffeescript, so wanted to ask.

**Comment by nmccready** [comment]
Yes I usually do; but it is way easier to review this way. It is tested as is (what you submited) on travis. It would be nice to have a post travis build task to auto magically keep master in sync with the code base.

**Comment by armyofda12mnkeys** [comment]
K @nmccready, so you will merge that PR request from 2.2.X into master soon? (cause the 1st PR fix without the 2nd PR might be bad)
See still the 2nd PR spacing fix didnt get merged into master yet (only 2.2.X).
https://github.com/angular-ui/angular-google-maps/blob/2.2.X/src/coffee/extensions/lodash.coffee
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/extensions/lodash.coffee

**Comment by nmccready** [comment]
I'll compile and push when  I get home

**Comment by nmccready** [comment]
Ok, I made a mistake by accepting both PRS, just issue them to master and I'll take care of syncing 2.2.X. Anyway they are back in sync and the mistakes are fixed.

**Pull request merged**
