### PR TITLE
(chore): Add packaging for Meteor.js

### PR DESCRIPTION
**Pull request by Urigo**
Hi @nmccready

I'm a package maintainer for Meteor.js, a popular [full-stack JavaScript framework](https://www.meteor.com/).

I'm also the creator of [angular-meteor](http://angularjs.meteor.com/), a library that let's you work with AngularJS on top of Meteor.

A lot of our users use angular-google-maps and right now there is a separate package and Github repo that simply manually copies your distribution and publish it to Meteor.

There is also a [tutorial about working with Meteor, AngularJS and angular-google-maps](http://angularjs.meteor.com/tutorial-02/step_16).

This PR is a start to allow you to directly publish updated versions of angular-google-maps to Meteor as they become available. 
All you have to do is create an account at https://meteor.com/ (click SIGN IN, then Create account). After you've done that, please let me know the name of the account, and I'll add you as a maintainer to the angularui organization there.

I've already published the current version of the package on Atmosphere (Meteor's package directory). When you release new versions of angular-google-maps, you'll be able to publish them to Atmosphere by running 

    meteor publish

There are also prepared grunt tasks for that but I wanted you to try to put them yourself as they are not in coffeescript.

Thanks & best regards,
Uri

### CODE REVIEW

**Comment by nmccready** [comment]
Ok, this sounds good. I will review it more when I get back home.

**Comment by nmccready** [comment]
It would be good if you pulled the `meteor publish` into our grunt release tasks.  
https://github.com/angular-ui/angular-google-maps/blob/master/Gruntfile.coffee#L85-L87

However, I should probably do this myself as those sometimes don't work out flawlessly. But publishing to npm and meteor should happen at the same-time.

**Comment by Urigo** [comment]
Yes you are right.
I just didn't want to do it without you.
Here is a reference to another pull request I've done to ui-router, in there you can see the code for Meteor publish:
https://github.com/MeteorPackaging/ui-router/commit/8f2e39e9780dee19201b4982ff6bbd98cf9f8770

It might help with translating it to your project and to coffeescript

**Comment by nmccready** [comment]
Just got home, I will dig into this today.

**Comment by nmccready** [comment]
I will merge this and see what I can do about the release part.

**Comment by nmccready** [comment]
Instead of making a grunt task; I kept it simple to a shell script for publishing https://github.com/angular-ui/angular-google-maps/commit/4c906292d9dc4fe867c5f3a7710f47ddef374121

**Comment by Urigo** [comment]
@nmccready amazing!

Let me know your Meteor username so I will add you to the organization

**Comment by nmccready** [comment]
@Urigo I made it uigmap (althought I didnt realize groups were available).  

Currently the user name is uigmap and the group is angulargooglemaps. If can switch the username to nmccready and the group to uigmap; that would be ideal.

**Comment by nmccready** [comment]
So far changing the username seems to be a pain or not easy.

**Comment by Urigo** [comment]
Won't it be better to make it angularui?

**Comment by nmccready** [comment]
Well I am just a peon in angularui and that requires more people to be involved. So if there is an angularui group already then yes I will use that.

**Comment by nmccready** [comment]
Who do I contact to get put into the angularui group for meteor?

**Comment by Urigo** [comment]
Me, it exists and ui-router is already there

**Comment by Urigo** [comment]
Also, I've already published angularui:angular-google-maps for version 2.0.12:
https://atmospherejs.com/angularui/angular-google-maps

**Comment by nmccready** [comment]
Ok how do I accept the group invite?

**Comment by nmccready** [comment]
Or just add uigmap account to angularui.

**Comment by Urigo** [comment]
Just added.
you can now deploy the next version with the name angularui:angular-google-maps

**Comment by nmccready** [comment]
Anything else I need to change or we should be set? I am about to push 2.0.13

**Comment by nmccready** [comment]
What do I need installed as a dev dependency to publish via `meteor publish`? It fails currently and 2.0.13 was cut.

**Comment by Urigo** [comment]
Have you updated the version in package.js?

Have you installed Meteor:

    curl https://install.meteor.com/ | sh

**Comment by nmccready** [comment]
`curl https://install.meteor.com/ | sh` should be integrated into the routine so it is seemless. This way I do not have to remember to install it.

**Comment by Urigo** [comment]
Yes that a good point....

**Comment by nmccready** [comment]
I wasnt sure if meteor needed to be installed via brew / npm or like you said manually.

**Comment by Urigo** [comment]
I guess there is no simpler then curl...

**Comment by nmccready** [comment]
Yeah, I have some code some where to test if the command alreayd exist and if not run it . (curl install sh)

**Comment by Urigo** [comment]
that's cool, I might share it with other people who sends similar pull requests

**Comment by nmccready** [comment]
Moving to #1190

**Pull request merged**
