### PR TITLE
Fix anchor target id for tab navigation on website FAQ.

### PR DESCRIPTION
**Pull request by rubenCodeforges**

### CODE REVIEW

**Comment by cthrax** [comment]
Did you run this locally? I seem to recall the spacing in those examples was required for something, but I could be totally making that up.

**Comment by nmccready** [comment]
@rubenCodeforges please respond or this will be closed in 3 days.

**Comment by rubenCodeforges** [comment]
@cthrax not localy , but from you website , it was very broken ( CHROME latest , Ubuntu 14.04 64x )

**Comment by cthrax** [comment]
@rubenCodeforges I must not be understanding something, what is this trying to fix? Are you saying this merge is currently broken?

**Comment by rubenCodeforges** [comment]
@cthrax  have you viewed the commits ? 
```
-    <li class="active"><a href="" data-target="#faq-map-instance-tab-html" data-toggle="tab">HTML</a></li>
 +    <li class="active"><a href="" data-target="#faq-map-instance-tab-html-js" data-toggle="tab">HTML</a></li>
```
You had `data-target="#faq-map-instance-tab-html"` but this is not correct target ( there is no such id )
i fixed it and `data-target="#faq-map-instance-tab-html-js"` notice the last `-js`

Then i did some code styling fixes

**Comment by cthrax** [comment]
@rubenCodeforges thanks for the clarification. The styling changes work correctly. LGTM.

**Pull request merged**
