### PR TITLE
Add config option to prevent loading Maps API

### PR DESCRIPTION
**Pull request by ralphsaunders**
Angular Google Maps loads the Google Maps API when Angular configures all
modules. This means the API is requested on every page load, which is
undesirable for Google Maps for Work customers who're charged on every page
view.

As outlined in issue [1604](https://github.com/angular-ui/angular-google-maps/issues/1604#issue-115128802) the ability to delay loading of the API would be beneficial.

This commit adds a new service to the google map API provider as well as a new
configuration option, `preventLoad: true`.

Here's how one would use this new feature to asynchronously load the API at a
later time in the Angular lifecycle:

    var app = angular.module('app', ['uiGmapgoogle-maps'])
        .config(['uiGmapGoogleMapApiProvider', function(uiGmapGoogleMapApiProvider)
        {
            var options = { preventLoad: true };
            uiGmapGoogleMapApiProvider.configure(options);
        }])
        .controller('myController', ['$scope', 'uiGmapGoogleMapApi', 'uiGmapGoogleMapApiManualLoader', function($scope, uiGmapGoogleMapApi, uiGmapGoogleMapApiManualLoader) {
            window.setTimeout(function() {
                uiGmapGoogleMapApiManualLoader.load();
            }, 2000);

            uiGmapGoogleMapApi.then(function(maps) {
                // Standard maps code
            });
        }])

I think I've managed to delete a lot of dot files and images in error here as part of this PR. I'm also not sure if this was the best way to go about extending angular-google-maps, although it did work for my purposes.

### CODE REVIEW

**Comment by nmccready** [comment]
Your on 2.1.X your need to PR to 2.1.X not master . Then I can attempt to roll it to 2.2.X / master. Otherwise change to 2.2.X and make the PR to master from there.

**Comment by adambezemek** [comment]
+1

**Comment by nmccready** [comment]
I would gladly merge this but it needs to come from 2.2.X

**Comment by webnerdlw** [comment]
Did this get merged into 2.2.1 and is part of the 2.2.1 release?  Please say yes.

**Comment by nmccready** [comment]
No the original person on the PR has not replied. The PR needs to be redirected to 2.1.X and then it can get kicked up to 2.2.X if there are not many conflicts.

**Comment by nmccready** [comment]
Attempting to merge this into 2.1.X since I got silence. Then I should be able to roll this into 2.2.X/master

**Comment by nmccready** [comment]
Merged with more work then necessary

**Comment by webnerdlw** [comment]
Thank you!  I appreciate the extra effort and hard work you do.

Lori Wilkins

**Pull request merged**
