### PR TITLE
Remove post-install script

### PR DESCRIPTION
**Pull request by julien-f**
It should not be done in post-install because these actions should only be done in development.

### CODE REVIEW

**Comment by nmccready** [comment]
So these are happening when npm installs it locally for dependencies?

**Comment by julien-f** [comment]
It happens everytime a package is installed ([source](https://docs.npmjs.com/misc/scripts)).

**Comment by nmccready** [comment]
Ok, well besides just removing it. Can you add a grunt task, or a script that still runs these. As this is very convenient for development. What would you suggest? I agree this should be removed; but what would be good for both worlds?

**Comment by julien-f** [comment]
To be honest, I am not familiar with your development process nor do I know grunt very well, I only wanted to install this package via npm.

One possible solution would be to create a custom `bootstrap` npm script and runs it manually:

```
> npm run bootstrap
```

**Comment by nmccready** [comment]
ok, yes `npm run` should be fine, I'll add that in to run the bower and curl dependencies at the same time.

**Comment by nmccready** [comment]
Not sure why this is not passing tests.

**Comment by julien-f** [comment]
Maybe you should add `bower install && grunt curl` in the [`before_scripts` of `.travis.yaml`](https://github.com/angular-ui/angular-google-maps/blob/master/.travis.yml#L4)?

**Comment by nmccready** [comment]
Actually grunt curl is required, bower is not required.

**Comment by nmccready** [comment]
bower is for the examples

**Comment by julien-f** [comment]
Ok :)

Thank you for the merge.

**Comment by nmccready** [comment]
Yes I think the travis recommendation will work.

**Pull request merged**
