### PR TITLE
Fix simple bug in SearchBoxParentModel constructor

### PR DESCRIPTION
**Pull request by avoid3d**
Simple enough bug :)

### CODE REVIEW

**Comment by nmccready** [comment]
I think this was already PR'ed to 2.0.X, I just need to roll it into here.

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/2.0.X/src/coffee/directives/api/models/parent/search-box-parent-model.coffee#L22-L23

**Comment by nmccready** [comment]
f1a3dd8ad27e9a02131e1e0e27addc344429729d

**Comment by nmccready** [comment]
Thanks for digging anyways .

**Comment by avoid3d** [comment]
No worries, this bug caused me so much pain :p

**Comment by nmccready** [comment]
new release cut

**Pull request closed without merging**
