### PR TITLE
modified searchbox example

### PR DESCRIPTION
**Pull request by kandizzy**
Let's see if this gets the places library to load within the plunkr in the API docs. The code works in Plunkr by itself.

### CODE REVIEW

**Comment by nmccready** [comment]
@kandizzy since your having problems with the loader possibly, can you add the google maps script day in the html and see if that fixes your issue? If so then there is a bug in the provider.

**Comment by nmccready** [comment]
Any updates on this, status wise?

**Comment by kandizzy** [comment]
Yeah, i'm working on it, but I still can't get the Plunkr's to load in localhost. Even if I hardcode the paths to the vendor scripts...

**Comment by kandizzy** [comment]
@nmccready just an update here, I made the examples run in localhost to test. i was able to make the example work by including the places lib directly in the HTML. Next step is to figure out why the provider is not loading the places lib.

**Comment by nmccready** [comment]
Ahh.. well this would be why Weather is not working as well.

**Comment by nmccready** [comment]
Heads up you guys are messing in the same domain.. #1567

**Comment by kandizzy** [comment]
cool. thanks, I'll return to this on the weekend so I'll check in with that PR.

**Comment by kandizzy** [comment]
@nmccready hey I haven't had a chance to get back at this, but I will this weekend. I will see if i can try to tackle some of the smaller issues where you've asked for a PR as well!

**Comment by nmccready** [comment]
Cool TY

**Comment by nmccready** [comment]
LGTM

**Pull request merged**
