### PR TITLE
Fix for getIcon method absence and options.content change on richmarker

### PR DESCRIPTION
**Pull request by caioiglesias**
When the model updates a check for icon updates, changes the icon when they in fact - change.

Since richmarker's icon resides inside options.content, that's where the check should be on this case.

### CODE REVIEW

**Comment by nmccready** [comment]
Any plans to add richmarker to the website docs?

**Comment by nmccready** [comment]
LGTM

**Comment by nmccready** [comment]
@caioiglesias could you start using angularjs commit conventions? It will help with the changelog.

**Comment by caioiglesias** [comment]
I will add it to the docs, and I'll look into the commit conventions too :)

**Pull request merged**
