### PR TITLE
Error fixed: When options are changed labelAnchor position goes back to 0,0 #1178

### PR DESCRIPTION
**Pull request by juancolacelli**
Sorry about my mistakes, I'm just trying to help. If I have more errors, please let me know it.

### CODE REVIEW

**Comment by nmccready** [comment]
No worries, sorry if that felt harsh. Also, are the other changes (many js changes) not needed?

**Comment by juancolacelli** [comment]
No, it was just me running "grunt mappAll" trying the changes. (My bad)

**Comment by juancolacelli** [comment]
When you change coords and an option like toggling visible true/false, the labelAnchor is reset to 0, 0 because it's bad formatted. That's the error that I'm solving.

**Comment by nmccready** [comment]
Please merge with latest code to see if travis starts working again. ty

**Comment by nmccready** [comment]
LGTM

**Pull request merged**
