### PR TITLE
spec tests bad?

### PR DESCRIPTION
**Pull request by armyofda12mnkeys**
Simplified the 'should add markers for each object in model' spec tests and at least 2 of them pass now (still 3 errors left, will look at those tomorrow).

I'm not big on coffeescript, so may want to review. I create the items array more like the 3rd 'should add markers for each object in model' test in the previous two tests.

like:
```
        toPush = {}
        toPush.id = 0
        toPush.latitude = 47
        toPush.longitude = -27
        @scope.items = [toPush]
```
instead of:
```
        toPush = {}
        toPush.id = 0
        toPush.latitude = 47
        toPush.longitude = -27
        @scope.items =
          0: toPush
          length: 1
```

and
like:
```
        items = []
        numarray = _.range(2) //wasnt sure if array was a protected var ame when converted to JS
        numarray.forEach (num) ->
          toPush = { id: num, latitude: 47, longitude: -27 }
          items[num] = toPush

        @scope.items = items
```
instead of:
```
        items  = {}
        array = _.range(2)
        items.length = array.length
        array.forEach (num) ->
          toPush =
            id: num
            latitude: 47
            longitude: -27

          items[num] = toPush

        @scope.items = items
```

### CODE REVIEW

**Comment by armyofda12mnkeys** [comment]
Think I meant to really merge that into dev/nmccready/tryingToMakeLodash4Wurk instead of master (sorry about that).
Anyway Travis also goes from 5 to 3 errors... so Progress?

**Comment by nmccready** [comment]
Those old test are valid. The iterator needs to support arrays and objects.

**Comment by armyofda12mnkeys** [comment]
So its been tough for me to debug because I can't see the actual JS that the spec coffee file creates (I thought it would be in tmp/ folder). Since I'm not strong with coffeescipt and more comfortable fixing the coffeescript files based on what I see compiled for JS, is there a way to see the compiled JS spec files? I see errors like on certain lines pretend (markers.spec.js:163 and model-key.spec.js:48) but can't figure out what exact expect() those actually are so I can add some console.log's to debug those areas.


Also just to focus on 1 thing to fix...
To support that 1st object test:
```
@scope.items =
          0: toPush
          length: 1
```

Where in the src code do you handle building the markers based on object (or array) so I can see what went wrong with objects in the build.

PS I'll close this PR soon since we wont be merging it.

**Comment by nmccready** [comment]
If you launch / modify the karma config to launch in browser :[Chrome] . It
will launch in chrome and you should see compiled JS.

https://github.com/angular-ui/angular-google-maps/blob/master/karma.conf.coffee#L75

**Comment by armyofda12mnkeys** [comment]
No dice on that Chrome option. Don't see any generated/compiled files anywhere after grunt is done.

**Comment by nmccready** [comment]
Thats because it is not pointed at the source mapped file. Edit [this](https://github.com/angular-ui/angular-google-maps/blob/master/karma.conf.coffee#L16) to use `angular-google-maps_dev_mapped.js`.

**Comment by nmccready** [comment]
Also u have to dig the debug folder structure in karma.

**Pull request closed without merging**
