### PR TITLE
Removes bounds watch when user triggers zoom on map with bounds set…

### PR DESCRIPTION
**Pull request by jcroughton**
…Fixes map re-fitting bounds after zoom, which seems unintuitive.

### CODE REVIEW

**Comment by nmccready** [comment]
People expect bounds watching to work. Not sure if this can be done. At the very least the docs would need to be updated. Can you show an example with your issue?

**Comment by nmccready** [comment]
I think there is going to need to be more compromise . Might need to add blacklist watches to scope. Any get me the example and I'll take a look, are you having issues with master cause that was recently updated. Wondering if there were regressions.

**Comment by jcroughton** [comment]
hi,

I have prepared plnkr's to demonstrate, thanks.

[https://plnkr.co/edit/zlgbFspQb6rN6q8XknEk?p=preview](https://plnkr.co/edit/zlgbFspQb6rN6q8XknEk?p=preview)

**Comment by cthrax** [comment]
Aren't you maybe attaching to the wrong event (tilesloaded)? Or not using it as an "onready" event like the comment seems to intend? Doing something like this appears to solve your issue, https://plnkr.co/edit/UdJ7z3lqqSljYrFgaYsk?p=preview

**Comment by jcroughton** [comment]
I see what you're doing and it does fix my issue. Though I think (IMHO) this is just a work-around to the issue that exists in angular-google-maps.

Will the fitBounds event still continuously fire inside angular-google-maps with your suggestion allowing us to bypass it?

Is it not better to de-register the event once it's achieved it's task? I don't know myself, hence the question. I often search for best practices to try and improve my code.

Appreciate there is also isReady but not sure if this works with browser resizing (which I require)?

**Comment by cthrax** [comment]
@jcroughton no "fit bounds" event fires. This is an artifact of angular databinding. Angular users expect that they get two-way databinding when using an expression on a directive. If "bounds" suddenly only bound (in the data sense) once, then it would be very non-intuitive to angular users.

**Comment by jcroughton** [comment]
Ok yes I see what you're saying. Essentially I appear to have amended angular-google-maps to work around a problem I created.

I will close this pull request and have implemented the suggested technique [(https://plnkr.co/edit/UdJ7z3lqqSljYrFgaYsk?p=preview)](https://plnkr.co/edit/UdJ7z3lqqSljYrFgaYsk?p=preview) of checking whether I need to run my fitBounds function.

Many thanks.

**Comment by cthrax** [comment]
No problem, thanks for jumping to a solution at least. Always appreciate help. :)

**Pull request closed without merging**
