### PR TITLE
fix(examples): searchbox

### PR DESCRIPTION
**Pull request by kandizzy**
- updated angular 1.3.8 to 1.5
- fixed error where marker clicks failed to open windows

### CODE REVIEW

**Comment by nmccready** [comment]
looks good, anyway you can undo the dist files and only submit the example changes?

**Comment by nmccready** [comment]
@kandizzy

**Comment by kandizzy** [comment]
@nmccready fixed

**Comment by nmccready** [comment]
try `git reset --hard ./dist cb5c8c2875eb2186710b8a9c3a0c91d408f885da`

**Comment by kandizzy** [comment]
there we go, just the modified files now.

**Comment by nmccready** [comment]
lgtm

**Pull request merged**
