### PR TITLE
Fix for issue #162 - onCreated callback not called

### PR DESCRIPTION
**Pull request by deleteman**
Guys, does this fix solve the issues with the onCreated callback not being called? The example works for me with this code.

### CODE REVIEW

**Comment by vinuthamsr** [comment]
Hi.. Could anyone confirm if heatmaps is available with angular-google-maps ? If so, please share an example.

**Comment by nmccready** [comment]
Yes it works, and there is an example in /examples in the source code base.

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/example/example.html#L58

**Comment by vinutha-singtel** [comment]
Thanks a lot! A great plugin.

**Pull request merged**
