### PR TITLE
(Meteor): Move dependencies to official 'angular' organization

### PR DESCRIPTION
**Pull request by Urigo**

### CODE REVIEW

**Comment by Urigo** [comment]
@nmccready I'm sorry but is there a chance to release a new version soon?

**Comment by nmccready** [comment]
@Urigo I am thinking of cutting 2.1.0 but I do not plan on updating the docs. 2.1.X has been stable for sometime, but the main thing it was on hold for is documentation.

**Comment by Urigo** [comment]
ohhh very cool
what are the breaking changes?

**Comment by Urigo** [comment]
anyway I would want you to release another 2.0 version as this dependency thing might cause problems later..

**Comment by nmccready** [comment]
Most of the breaking changes are in Shapes where expressions are supported and the old model string paths are(possibly) not. Overall markers and windows support expressions and the old models (string props) for bindable properties.

**Comment by Urigo** [comment]
very cool

**Pull request merged**
