### PR TITLE
Richmarker

### LINKED ISSUE #607: RichMarker
How to use RichMarker class in markers directive?

### PR DESCRIPTION
**Pull request by caioiglesias**
Adding HTML to marker or markers' option content variable generates a richmarker.

Demo at http://plnkr.co/edit/xZTVxn1kFp2HM49tdD6o?p=preview

Closes #607

### CODE REVIEW

**Comment by nmccready** [comment]
You PR won't be merged if it is failing. Please fix.

**Comment by nmccready** [comment]
Well it looks like travis is messed up. Need to fix that first.

**Comment by caioiglesias** [comment]
From the build log:

Warning: An error occurred while processing a template (Unable to read "bower_components/uuid/dist/uuid.core.js" file (Error code: ENOENT).). Use --force to continue.

**Comment by caioiglesias** [comment]
It's apparently skipping the install part on the bower task

**Comment by caioiglesias** [comment]
Ok, got it.

Bower wasn't sure which angular version to install.

Unable to find a suitable version for angular, please choose one:
    1) angular#1.3.15 which resolved to 1.3.15 and is required by angular-route#1.3.15
    2) angular#>=1.4.0 which resolved to 1.4.0 and is required by angular-google-maps
    3) angular#1.4.0 which resolved to 1.4.0 and is required by angular-mocks#1.4.0

I updated angular and angular-route to 1.4.0 on bower.json

**Comment by nmccready** [comment]
Yeah the bower stuff is why travis is broken. I know it works on 1.3.15 so I set it to that.

**Comment by nmccready** [comment]
Says it still can't be auto-merged.

**Comment by caioiglesias** [comment]
Alright! Tweaked it.

**Comment by nmccready** [comment]
Lgtm

**Pull request merged**
