### PR TITLE
Fix #1236: When a Markers tag is destroyed, a null cancelCb triggers an error

### LINKED ISSUE #1236: When a Markers tag is destroyed, a null cancelCb triggers an error
TypeError: object is not a function
    at Object.cancelLogger [as cancelCb] (file:///android_asset/www/lib/angular-google-maps/dist/angular-google-maps.js:466:18)
    at maybeCancelPromises (file:///android_asset/www/lib/angular-google-maps/dist/angular-google-maps.js:386:25)
    at PromiseQueueManager (file:///android_asset/www/lib/angular-google-maps/dist/angular-google-maps.js:447:11)
    at Object.managePromiseQueue (file:///android_asset/www/lib/angular-google-maps/dist/angular-google-maps.js:468:16)
    at MarkersParentModel.onDestroy (file:///android_asset/www/lib/angular-google-maps/dist/angular-google-maps.js:4337:25)
    at MarkersParentModel.<anonymous> (file:///android_asset/www/lib/angular-google-maps/dist/angular-google-maps.js:4090:63)
    at MarkersParentModel.onDestroy (file:///android_asset/www/lib/angular-google-maps/dist/angular-google-maps.js:3768:63)
    at file:///android_asset/www/lib/angular-google-maps/dist/angular-google-maps.js:3803:28
    at k.$broadcast (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:145:327)
    at k.$destroy (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:141:440) 

The code seems to be entirely internal to angular-google-maps, and the root cause seems to be in `src/coffee/directives/api/models/parent/markers-parent-model.coffee`:

    _async.promiseLock @, uiGmapPromise.promiseTypes.delete, undefined, undefined, =>

Notice the 4th argument being `undefined`.

I will provide a PR in a few minutes.

### PR DESCRIPTION
**Pull request by siovene**

### CODE REVIEW

**Comment by siovene** [comment]
Note that I didn't bother with the failed unit tests because they fail on master too.

**Comment by nmccready** [comment]
Let me fix the specs before I merge this.

**Comment by nmccready** [comment]
I think something broke with angular mocks.. I seriously still have not figured it out. Anyone see any change log stuff?

**Comment by nmccready** [comment]
Think I found the issue. Looks like jasmine broke some compatibility which breaks angular.mocks. `window.jasmine` is undefined which causes the mock module globals to not be defined.

**Comment by nmccready** [comment]
Please fetch updates and push back up so I can check that things still pass.

**Comment by siovene** [comment]
Done!

**Comment by nmccready** [comment]
@siovene can you cherry pick your changes to 2.0.X merging to master is for 2.1.X. If you do another PR you get cred.

**Comment by siovene** [comment]
Sure, I can do it tomorrow.

**Comment by nmccready** [comment]
:+1:

**Pull request merged**
